### ISSUE TITLE
How to unpack the fgimage?

### ISSUE THREAD

**Issue by SummerOfIce** [lictex/atri-composite#1]
I tried to use GARbro to unpack them,but it seems that they were  encrypted.All extracted PNG files cannot be displayed.

**Comment by lictex** [comment]
official GARbro releases hasnt been updated for a while so it likely cant decrypt newer games...
someone provided a new database here https://github.com/morkt/GARbro/issues/425#issuecomment-660663750. try replacing `GARbro/GameData/Formats.dat` with it, then atri should appear in GARbro's encryption list
edit: theres also a modded version of GARbro in that issue which should also work, you could give it a try

**Comment by SummerOfIce** [comment]
Thanks!It works!

**Comment by SummerOfIce** [comment]
> official GARbro releases hasnt been updated for a while so it likely cant decrypt newer games... someone provided a new database here [morkt/GARbro#425 (comment)](https://github.com/morkt/GARbro/issues/425#issuecomment-660663750). try replacing `GARbro/GameData/Formats.dat` with it, then atri should appear in GARbro's encryption list edit: theres also a modded version of GARbro in that issue which should also work, you could give it a try


你好，很高兴两年后又看到你又做了ginka的适配，但是我没有找到可以解包ginka的GARbro，请问如何解包ginka呢？谢谢！

**Comment by lictex** [comment]
记得当时是 krkrdump 解的包（输出文件似乎不太全但够用了
https://github.com/crskycode/GARbro/issues/14#issuecomment-1817729221 看起来也行

**Comment by SummerOfIce** [comment]
> 记得当时是 krkrdump 解的包（输出文件似乎不太全但够用了 [crskycode/GARbro#14 (comment)](https://github.com/crskycode/GARbro/issues/14#issuecomment-1817729221) 看起来也行

谢谢大佬！
