### ISSUE TITLE
大佬有兴趣做GINKA的立绘合成器吗

### ISSUE THREAD

**Issue by Cheems0721** [lictex/atri-composite#6]
因为两者立绘文件结构都差不多，我尝试将GINKA立绘文件摆放和ATRI一致，结果打开合成器读取就闪退..
![QQ截图20231102123046](https://github.com/lictex/atri-composite/assets/112457136/d7895538-8c56-4bd0-88a5-515efd284242)

**Comment by lictex** [comment]
[v1.4](https://github.com/lictex/atri-composite/releases/tag/v1.4)

**Comment by SummerOfIce** [comment]
> 因为两者立绘文件结构都差不多，我尝试将GINKA立绘文件摆放和ATRI一致，结果打开合成器读取就闪退.. ![QQ截图20231102123046](https://private-user-images.githubusercontent.com/112457136/279866762-d7895538-8c56-4bd0-88a5-515efd284242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MTk1ODEsIm5iZiI6MTcxOTQxOTI4MSwicGF0aCI6Ii8xMTI0NTcxMzYvMjc5ODY2NzYyLWQ3ODk1NTM4LThjNTYtNGJkMC04OGE1LTUxNWVmZDI4NDI0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxNjI4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NmZlN2VjOWExZGQ0NGM0MDk2N2JhMzAzZjlmMjRmYWMyOWE0ZjZiMGU0NzlmZDQ5MTAwOWYwODg3ZDY3MTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yp79ck5NVVL82qR3NTKc1TzK6gODBjz-iml-VU_4EXo)

请问你是如何得到ginka的立绘文件的？我找了很多方法但还是缺一些文件，谢谢！
