### ISSUE TITLE
想请教一下你是如何实现pbd2json的

### ISSUE THREAD

**Issue by bGlzdGRlcg** [lictex/atri-composite#7]
RT

**Comment by lictex** [comment]
... <s>偷</s>借他的库出来再简单打个包
<details>

![image](https://github.com/lictex/atri-composite/assets/13201009/ef901a83-86c8-469c-9e25-058b20e804d4)
所以我也没有真正的源代码，但是能用
并不知道这 dll 什么许可证 + 能不能再分发（虽然大概也没人管）因此封一层在表面掩盖一下（
</details>

**Comment by bGlzdGRlcg** [comment]
原来如此，谢谢了
